env:
  browser: true
  es2021: true
  node: true
  jest: true
plugins:
  - jest
extends:
  - airbnb-base
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
  no-console: 0
}
