language: node_js

node_js:
  - node

env:
  global:
    - CC_TEST_REPORTER_ID=5f964e413e3b438fa24acde931e5207e6725d46700e3a6616c2cb009292b4a7c
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - make lint
  - make test-coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email: false
